/**
 * AGENTS.md adapter: export-only.
 *
 * Import is not supported in v0.1 because AGENTS.md is too
 * unstructured to parse reliably into discrete rules.
 */

import { access, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type {
	ExportOptions,
	ExportResult,
	ImportResult,
	Rule,
	RuleCategory,
	RulixAdapter,
	TokenBudget,
} from "../core/ir.js";

const AGENTS_MD = "AGENTS.md";
const GENERATED_HEADER =
	"<!-- Generated by Rulix. Do not edit directly. -->\n\n";

const CATEGORY_LABELS: Record<RuleCategory, string> = {
	style: "Style",
	security: "Security",
	testing: "Testing",
	architecture: "Architecture",
	workflow: "Workflow",
	general: "General",
};

const CATEGORY_ORDER: RuleCategory[] = [
	"architecture",
	"style",
	"security",
	"testing",
	"workflow",
	"general",
];

// ─── Filesystem Helpers ──────────────────────────────────────────

async function pathExists(filePath: string): Promise<boolean> {
	try {
		await access(filePath);
		return true;
	} catch {
		return false;
	}
}

// ─── Export Helpers ──────────────────────────────────────────────

function groupByCategory(rules: Rule[]): Map<RuleCategory, Rule[]> {
	const groups = new Map<RuleCategory, Rule[]>();

	for (const rule of rules) {
		const existing = groups.get(rule.category);
		if (existing) {
			existing.push(rule);
		} else {
			groups.set(rule.category, [rule]);
		}
	}

	return groups;
}

function buildCategorySection(category: RuleCategory, rules: Rule[]): string {
	const sorted = [...rules].sort((a, b) => a.priority - b.priority);
	const label = CATEGORY_LABELS[category];
	const sections = sorted.map((r) => `### ${r.description}\n\n${r.content}`);
	return `## ${label}\n\n${sections.join("\n\n")}`;
}

function buildAgentsMdContent(rules: Rule[], includeHeader: boolean): string {
	if (rules.length === 0) return "";

	const groups = groupByCategory(rules);
	const sections: string[] = [];

	for (const category of CATEGORY_ORDER) {
		const categoryRules = groups.get(category);
		if (categoryRules && categoryRules.length > 0) {
			sections.push(buildCategorySection(category, categoryRules));
		}
	}

	const header = includeHeader ? GENERATED_HEADER : "";
	return `${header}# AGENTS.md\n\n${sections.join("\n\n")}\n`;
}

// ─── Adapter ─────────────────────────────────────────────────────

export const agentsMdAdapter: RulixAdapter = {
	name: "agents-md",
	displayName: "AGENTS.md",

	async detect(projectRoot: string): Promise<boolean> {
		return pathExists(join(projectRoot, AGENTS_MD));
	},

	async import(_projectRoot: string): Promise<ImportResult> {
		return { rules: [], warnings: [], source: AGENTS_MD };
	},

	async export(
		rules: Rule[],
		projectRoot: string,
		options?: ExportOptions,
	): Promise<ExportResult> {
		const dryRun = options?.dryRun === true;
		const content = buildAgentsMdContent(rules, true);

		if (content === "") {
			return { filesWritten: [], filesDeleted: [], warnings: [] };
		}

		if (!dryRun) {
			await writeFile(join(projectRoot, AGENTS_MD), content, "utf-8");
		}

		return {
			filesWritten: [AGENTS_MD],
			filesDeleted: [],
			warnings: [],
		};
	},

	getTokenBudget(): TokenBudget {
		return {
			maxTokens: 32_768,
			warningThreshold: 0.8,
			source: "AGENTS.md convention",
		};
	},
};
