/**
 * Intermediate Representation (IR) types for Rulix.
 *
 * All logic operates on these types, never on raw tool-specific formats.
 * This module defines the core contract between the engine and adapters.
 */

// ─── Scalar Types ────────────────────────────────────────────────

export type RuleScope = "always" | "file-scoped" | "agent-selected";

export type RuleCategory =
	| "style"
	| "security"
	| "testing"
	| "architecture"
	| "workflow"
	| "general";

export type ValidationSeverity = "error" | "warning" | "info";

export type ExportStrategy = "overwrite" | "merge";

export type TokenEstimation = "heuristic" | "tiktoken";

export type ClaudeMdStrategy = "concatenate" | "reference";

// ─── Result Pattern ──────────────────────────────────────────────

/**
 * Use for operations that can fail in predictable ways (parsing, validation).
 * Reserve exceptions for unexpected errors (filesystem, permissions).
 */
export type Result<T, E = RulixError> =
	| { readonly ok: true; readonly value: T }
	| { readonly ok: false; readonly error: E };

/**
 * Every error carries a machine-readable `code` so callers can handle
 * specific failure modes programmatically without parsing message strings.
 */
export class RulixError extends Error {
	public override readonly name = "RulixError";

	constructor(
		public readonly code: string,
		message: string,
		public override readonly cause?: unknown,
	) {
		super(message);
	}
}

// ─── Core IR ─────────────────────────────────────────────────────

/**
 * Tracks where a rule was imported from so users can trace back
 * to the original source file when debugging conflicts.
 */
export interface RuleSource {
	/** E.g. `"cursor"`, `"claude-code"`, `"rulix"`. */
	readonly adapter: string;
	/** Relative to the project root. */
	readonly filePath: string;
	/** ISO 8601 timestamp. */
	readonly importedAt: string;
}

/**
 * The fundamental unit of the Rulix IR. All adapters convert
 * their tool-specific formats to and from this representation.
 */
export interface Rule {
	/** Kebab-case. Used for deduplication and preset composition. */
	readonly id: string;
	readonly scope: RuleScope;
	/** Used by agent-selected rules to let the AI decide relevance. */
	readonly description: string;
	readonly content: string;
	/** Required when `scope` is `"file-scoped"`. */
	readonly globs?: string[];
	readonly category: RuleCategory;
	/** 1 (critical) to 5 (nice-to-have). Drives token budget optimization. */
	readonly priority: number;
	/** E.g. `"@rulix/typescript/strict"`. */
	readonly extends?: string;
	/** Auto-computed by the tokenizer. */
	readonly estimatedTokens: number;
	readonly source?: RuleSource;
}

export interface RulixConfigOptions {
	readonly tokenEstimation: TokenEstimation;
	/** Controls the "Generated by Rulix" header in AGENTS.md output. */
	readonly agentsMdHeader: boolean;
	readonly claudeMdStrategy: ClaudeMdStrategy;
	/** Used by the `watch` command. */
	readonly syncOnSave: boolean;
}

/**
 * Fully-resolved project configuration with all defaults applied.
 */
export interface RulixConfig {
	/** Adapter names, e.g. `["cursor", "claude-code", "agents-md"]`. */
	readonly targets: string[];
	/** npm packages or local paths to preset rule collections. */
	readonly presets: string[];
	/** Keyed by rule ID. */
	readonly overrides: Record<string, Partial<Rule>>;
	readonly options: RulixConfigOptions;
}

export interface Ruleset {
	/** Local + preset rules, after overrides are applied. */
	readonly rules: Rule[];
	readonly config: RulixConfig;
}

// ─── Adapter Interface ───────────────────────────────────────────

/**
 * Each adapter provides its own budget based on the tool's known limits
 * (e.g. Claude Code ~150 instructions, Cursor ~500).
 */
export interface TokenBudget {
	readonly maxTokens: number;
	readonly maxInstructions: number;
	/** Fraction of max (e.g. 0.8 for 80%). */
	readonly warningThreshold: number;
	/** Where the limit comes from (e.g. documentation URL). */
	readonly source: string;
}

export interface ExportOptions {
	readonly strategy: ExportStrategy;
	/** Preview changes without writing to disk. */
	readonly dryRun?: boolean | undefined;
}

export interface ImportWarning {
	readonly ruleId?: string | undefined;
	/** Source file that produced the warning. */
	readonly filePath: string;
	readonly message: string;
}

export interface ExportWarning {
	readonly ruleId?: string | undefined;
	/** Target file that produced the warning. */
	readonly filePath: string;
	readonly message: string;
}

export interface ImportResult {
	readonly rules: Rule[];
	readonly warnings: ImportWarning[];
	/** E.g. `".cursor/rules/"`. */
	readonly source: string;
}

export interface ExportResult {
	readonly filesWritten: string[];
	/** Files removed because the corresponding rule was deleted from source. */
	readonly filesDeleted: string[];
	readonly warnings: ExportWarning[];
}

/**
 * Contract that every tool-specific adapter must implement.
 *
 * Import reads tool-specific files into `Rule[]`; export writes `Rule[]`
 * back to the tool's native format.
 */
export interface RulixAdapter {
	/** E.g. `"cursor"`, `"claude-code"`. */
	readonly name: string;
	/** E.g. `"Cursor"`, `"Claude Code"`. */
	readonly displayName: string;

	detect(projectRoot: string): Promise<boolean>;
	import(projectRoot: string): Promise<ImportResult>;
	export(
		rules: Rule[],
		projectRoot: string,
		options?: ExportOptions,
	): Promise<ExportResult>;
	getTokenBudget(): TokenBudget;
}

// ─── Validation ──────────────────────────────────────────────────

/**
 * Codes follow the pattern `V001`–`V999` as defined in PRD section 11.1.
 */
export interface ValidationIssue {
	/** E.g. `"V001"`. */
	readonly code: string;
	readonly severity: ValidationSeverity;
	readonly message: string;
	readonly ruleId?: string | undefined;
	readonly filePath?: string | undefined;
	/** Actionable fix suggestion. */
	readonly suggestion?: string | undefined;
}

export interface ValidationResult {
	/** `true` when no errors were found (warnings and info are allowed). */
	readonly passed: boolean;
	readonly errors: ValidationIssue[];
	readonly warnings: ValidationIssue[];
	readonly info: ValidationIssue[];
}
