import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { agentsMdAdapter } from "../../src/adapters/agents-md.js";
import type { Rule } from "../../src/core/ir.js";

let tmpDir: string;

beforeEach(async () => {
	tmpDir = join(tmpdir(), `rulix-agents-md-test-${Date.now()}`);
	await mkdir(tmpDir, { recursive: true });
});

afterEach(async () => {
	await rm(tmpDir, { recursive: true, force: true });
});

function makeRule(overrides: Partial<Rule> = {}): Rule {
	return {
		id: "test-rule",
		scope: "always",
		description: "A test rule",
		content: "Follow this convention.",
		category: "style",
		priority: 1,
		estimatedTokens: 10,
		...overrides,
	};
}

// ─── detect ──────────────────────────────────────────────────────

describe("detect", () => {
	it("returns false when AGENTS.md does not exist", async () => {
		expect(await agentsMdAdapter.detect(tmpDir)).toBe(false);
	});

	it("returns true when AGENTS.md exists", async () => {
		await writeFile(join(tmpDir, "AGENTS.md"), "# AGENTS.md");
		expect(await agentsMdAdapter.detect(tmpDir)).toBe(true);
	});
});

// ─── import ──────────────────────────────────────────────────────

describe("import", () => {
	it("returns empty results (import not supported)", async () => {
		await writeFile(join(tmpDir, "AGENTS.md"), "# Some content");

		const result = await agentsMdAdapter.import(tmpDir);
		expect(result.rules).toHaveLength(0);
		expect(result.warnings).toHaveLength(0);
	});
});

// ─── export ──────────────────────────────────────────────────────

describe("export", () => {
	it("writes AGENTS.md with generated header", async () => {
		const rules = [makeRule()];
		await agentsMdAdapter.export(rules, tmpDir);

		const content = await readFile(join(tmpDir, "AGENTS.md"), "utf-8");
		expect(content).toContain(
			"<!-- Generated by Rulix. Do not edit directly. -->",
		);
	});

	it("groups rules by category with H2 headers", async () => {
		const rules = [
			makeRule({
				id: "style-rule",
				category: "style",
				description: "Style Rule",
				content: "Use tabs.",
			}),
			makeRule({
				id: "security-rule",
				category: "security",
				description: "Security Rule",
				content: "Validate inputs.",
			}),
		];
		await agentsMdAdapter.export(rules, tmpDir);

		const content = await readFile(join(tmpDir, "AGENTS.md"), "utf-8");
		expect(content).toContain("## Style");
		expect(content).toContain("## Security");
		expect(content).toContain("### Style Rule");
		expect(content).toContain("### Security Rule");
	});

	it("orders categories consistently", async () => {
		const rules = [
			makeRule({ id: "general", category: "general", description: "General" }),
			makeRule({ id: "arch", category: "architecture", description: "Arch" }),
		];
		await agentsMdAdapter.export(rules, tmpDir);

		const content = await readFile(join(tmpDir, "AGENTS.md"), "utf-8");
		const archIdx = content.indexOf("## Architecture");
		const generalIdx = content.indexOf("## General");
		expect(archIdx).toBeLessThan(generalIdx);
	});

	it("orders rules within a category by priority", async () => {
		const rules = [
			makeRule({
				id: "low",
				category: "style",
				description: "Low Priority",
				priority: 5,
			}),
			makeRule({
				id: "high",
				category: "style",
				description: "High Priority",
				priority: 1,
			}),
		];
		await agentsMdAdapter.export(rules, tmpDir);

		const content = await readFile(join(tmpDir, "AGENTS.md"), "utf-8");
		const highIdx = content.indexOf("### High Priority");
		const lowIdx = content.indexOf("### Low Priority");
		expect(highIdx).toBeLessThan(lowIdx);
	});

	it("includes all scopes in output", async () => {
		const rules = [
			makeRule({ id: "always", scope: "always", description: "Always" }),
			makeRule({
				id: "scoped",
				scope: "file-scoped",
				description: "Scoped",
				globs: ["**/*.ts"],
			}),
			makeRule({
				id: "agent",
				scope: "agent-selected",
				description: "Agent",
			}),
		];
		await agentsMdAdapter.export(rules, tmpDir);

		const content = await readFile(join(tmpDir, "AGENTS.md"), "utf-8");
		expect(content).toContain("### Always");
		expect(content).toContain("### Scoped");
		expect(content).toContain("### Agent");
	});

	it("supports dry run without writing", async () => {
		const rules = [makeRule()];
		const result = await agentsMdAdapter.export(rules, tmpDir, {
			strategy: "overwrite",
			dryRun: true,
		});

		expect(result.filesWritten).toHaveLength(1);
		const exists = await readFile(join(tmpDir, "AGENTS.md"), "utf-8").catch(
			() => null,
		);
		expect(exists).toBeNull();
	});

	it("includes rule content in output", async () => {
		const rules = [
			makeRule({
				id: "my-rule",
				description: "My Rule",
				content: "- Use strict mode\n- No any types",
			}),
		];
		await agentsMdAdapter.export(rules, tmpDir);

		const content = await readFile(join(tmpDir, "AGENTS.md"), "utf-8");
		expect(content).toContain("- Use strict mode");
		expect(content).toContain("- No any types");
	});

	it("never deletes files", async () => {
		const rules = [makeRule()];
		const result = await agentsMdAdapter.export(rules, tmpDir, {
			strategy: "overwrite",
		});

		expect(result.filesDeleted).toHaveLength(0);
	});
});

// ─── getTokenBudget ──────────────────────────────────────────────

describe("getTokenBudget", () => {
	it("returns AGENTS.md token budget", () => {
		const budget = agentsMdAdapter.getTokenBudget();
		expect(budget.maxTokens).toBe(32_768);
		expect(budget.warningThreshold).toBe(0.8);
	});
});
